version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/APP/NEXT_APP"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      app-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        versions:
          - "*beta*"
          - "*alpha*"
          - "*rc*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
