-- AlterEnum
ALTER TYPE "JobSource" ADD VALUE 'GETONBOARD';
ALTER TYPE "JobSource" ADD VALUE 'TRABAJANDO';
ALTER TYPE "JobSource" ADD VALUE 'CHILETRABAJOS';
ALTER TYPE "JobSource" ADD VALUE 'HIRELINE';
ALTER TYPE "JobSource" ADD VALUE 'TORRE';
ALTER TYPE "JobSource" ADD VALUE 'WORKANA';
